   RAW HTML FOR:
   http://finance.yahoo.com/news/cisco-announces-agreement-acquire-sourcef
   ire-120000871.html

     * Home
     * [1]Mail
     * [2]Flickr
     * [3]Tumblr
     * [4]News
     * [5]Sports
     * [6]Finance
     * [7]Celebrity
     * [8]Answers
     * [9]Groups
     * [10]Mobile
     * [11]More
     * [12]Firefox Try Yahoo Finance on Firefox »

   [13]Yahoo
   Search
   ____________________

                       (BUTTON) Search
     * [14]Sign in
     * [15]Mail

   [16]Finance Home
     * Originals
     * Events
     * [17]Personal Finance
     * [18]Technology
     * Markets
     * Industries
     * [spaceball.gif]
       My Screeners
     * [19]My Portfolio

   U.S. Markets close in 1 hr 57 mins
     * [20]S&P 500
       2,343.52
       -5.73 (-0.24%)
     * [21]Dow 30
       20,588.41
       -23.45 (-0.11%)

   (BUTTON) (BUTTON)

Cisco Announces Agreement to Acquire Sourcefire

   [22]Marketwired
   [23]MarketwiredJuly 23, 2013
   (BUTTON)
   Reblog
   (BUTTON)
   Share
   (BUTTON)
   Tweet
   (BUTTON)
   Share

   SAN JOSE, CA and COLUMBIA, MD--(Marketwired - Jul 23, 2013) - Cisco (
   NASDAQ : CSCO ) and Sourcefire ( NASDAQ : FIRE ) today announced a
   definitive agreement for Cisco to acquire Sourcefire, a leader in
   intelligent cybersecurity solutions. Cisco and Sourcefire will combine
   their world-class products, technologies and research teams to provide
   continuous and pervasive advanced threat protection across the entire
   attack continuum -- before, during and after an attack -- and from any
   device to any cloud.

   Mobility, cloud and the evolution of the "Internet of Everything" are
   drastically changing today's IT security landscape, making traditional
   disparate products insufficient to protect organizations from dynamic
   threats. Sourcefire delivers innovative, highly automated security
   through continuous awareness, threat detection and protection across
   its industry-leading portfolio, including next-generation intrusion
   prevention systems, next-generation firewalls, and advanced malware
   protection.

   The acquisition of Sourcefire adds a team with deep security DNA to
   Cisco and will accelerate delivery of Cisco's security strategy of
   defending, discovering, and remediating advanced threats. With
   world-class research teams, increased intelligence and expanded threat
   protection, customers will benefit from continuous security in more
   places across the network.

   Under the terms of the agreement, Cisco will pay $76 per share in cash
   in exchange for each share of Sourcefire and assume outstanding equity
   awards for an aggregate purchase price of approximately $2.7 billion,
   including retention-based incentives. The acquisition has been approved
   by the board of directors of each company.

   "'Buy' has always been a key part of our build-buy-partner innovation
   strategy," said Hilton Romanski, vice president, Cisco Corporate
   Development. "Sourcefire aligns well with Cisco's future vision for
   security and supports the key pillars of our security strategy. Through
   our shared view of the critical role the network must play in
   cybersecurity and threat defense, we have a unique opportunity to
   deliver the most comprehensive approach to security in the market."

   "The notion of the 'perimeter' no longer exists and today's
   sophisticated threats are able to circumvent traditional, disparate
   security products. Organizations require continuous and pervasive
   advanced threat protection that addresses each phase of the attack
   continuum," said Christopher Young, senior vice president, Cisco
   Security Group. "With the acquisition of Sourcefire, we believe our
   customers will benefit from one of the industry's most comprehensive,
   integrated security solutions -- one that is simpler to deploy, and
   offers better security intelligence."

   "Cisco's acquisition of Sourcefire will help accelerate the realization
   of our vision for a new model of security across the extended network,"
   said Martin Roesch, founder and chief technology officer of Sourcefire.
   "We're excited about the opportunities ahead to expand our footprint
   via Cisco's global reach, as well as Cisco's commitment to support our
   pace of innovation in both commercial markets and the open source
   community."

   The acquisition is expected to close during the second half of calendar
   year 2013, subject to customary closing conditions and regulatory
   reviews. Cisco expects the acquisition to be slightly dilutive to
   non-GAAP earnings in fiscal year 2014 due to normal purchase accounting
   adjustments and integration costs. Once the transaction closes, Cisco
   will include Sourcefire into its guidance going forward. Prior to the
   close, Cisco and Sourcefire will continue to operate as separate
   companies. Upon completion of the transaction Sourcefire employees will
   join the Cisco Security Group led by Christopher Young.

   Sourcefire was founded in 2001 and completed its initial public
   offering in 2007. The company is based in Columbia, MD, an area widely
   recognized as a center of excellence for security innovation, and has
   more than 650 employees worldwide. For the full year ended December 31,
   2012, Sourcefire reported revenue of $223.1 million, an increase of 35
   percent year-over-year.

   Editor's Note
     * Cisco and Sourcefire will host a joint investor call on July 23 at
       6:00 a.m. PDT/9:00 a.m. EDT to discuss the proposed transaction.
       Conference call number is toll free 1-888-788-8648 or international
       1-517-308-9239.
     * Conference call replay will be available approximately one hour
       after the conclusion of the event on July 23 through August 6 at
       toll free 1-888-562-6119 or international 1-203-369-3186. The
       webcast replay will also be available via Cisco's Investor
       Relations website at [24]http://investor.cisco.com.
     * Speakers will include: Hilton Romanski, vice president, Corporate
       Development, Cisco; Christopher Young, senior vice president,
       Security Group, Cisco; and Martin Roesch, founder and chief
       technology officer, Sourcefire.

   About Cisco

   Cisco ( NASDAQ : CSCO ) is the worldwide leader in IT that helps
   companies seize the opportunities of tomorrow by proving that amazing
   things can happen when you connect the previously unconnected. For
   ongoing news, please go to [25]http://thenetwork.cisco.com.
   (BUTTON) Read More

   About Sourcefire

   Sourcefire, Inc. ( NASDAQ : FIRE ), a world leader in intelligent
   cybersecurity solutions, is transforming the way global large- to
   mid-size organizations and government agencies manage and minimize
   security risks to their dynamic networks, endpoints, mobile devices and
   virtual environments. With solutions from a next-generation network
   security platform to advanced malware protection, Sourcefire's
   threat-centric approach provides customers with Agile Security^® that
   delivers protection Before, During and After™ an attack. Trusted for
   more than 10 years, Sourcefire has earned a reputation for innovation,
   consistent security effectiveness and world-class research all focused
   on detecting, understanding and stopping threats. For more information
   about Sourcefire, please visit [26]www.sourcefire.com.

   Cisco and the Cisco logo are trademarks or registered trademarks of
   Cisco and/or its affiliates in the U.S. and other countries. A listing
   of Cisco's trademarks can be found at [27]www.cisco.com/go/trademarks.
   Third-party trademarks mentioned are the property of their respective
   owners. The use of the word partner does not imply a partnership
   relationship between Cisco and any other company.

   Sourcefire, the Sourcefire logo, Snort, the Snort and Pig logo, Agile
   Security and the Agile Security logo, 'Before, During, and After,'
   ClamAV, FireAMP, FirePOWER, FireSIGHT and certain other trademarks and
   logos are trademarks or registered trademarks of Sourcefire, Inc. in
   the United States and other countries. Other company, product and
   service names may be trademarks or service marks of others.

   Forward-Looking Statements

   This written communication may be deemed to contain forward-looking
   statements, which are subject to the safe harbor provisions of the
   Private Securities Litigation Reform Act of 1995, including statements
   regarding the combination of the companies' products and technologies
   to provide continuous and pervasive advanced threat protection across
   the entire attack continuum and from any device to any cloud, the
   acceleration of delivery of Cisco's security strategy as a result of
   the acquisition, the delivery of a new continuous security approach for
   customers, the acceleration of the realization of the vision for a new
   model of security across the extended network, the expected completion
   of the acquisition and the time frame in which this will occur, the
   expected benefits to Cisco and its customers from completing the
   acquisition, the expected financial performance of Cisco (including
   earnings projections) following completion of the acquisition, and
   plans regarding Sourcefire personnel. Statements regarding future
   events are based on the parties' current expectations and are
   necessarily subject to associated risks related to, among other things,
   obtaining Sourcefire's stockholder and regulatory approval of the
   acquisition or that other conditions to the closing of the transaction
   may not be satisfied, the potential impact on the business of
   Sourcefire due to the uncertainty about the acquisition, the occurrence
   of any event, change or other circumstances that could give rise to the
   termination of the definitive agreement, the outcome of any legal
   proceedings related to the transaction, general economic conditions,
   the retention of employees of Sourcefire and the ability of Cisco to
   successfully integrate Sourcefire's market opportunities, technology,
   personnel and operations and to achieve expected benefits. Therefore,
   actual results may differ materially and adversely from those expressed
   in any forward-looking statements. For information regarding other
   related risks, see the "Risk Factors" section of Cisco's most recent
   reports on Form 10-K and Form 10-Q filed with the SEC on September 12,
   2012 and May 21, 2013, respectively, as well as the "Risk Factors"
   section of Sourcefire's most recent reports on Form 10-K and Form 10-Q
   filed with the SEC on February 28, 2013 and May 3, 2013, respectively.
   The parties undertake no obligation to revise or update any
   forward-looking statements for any reason.

   Additional Information and Where to Find It

   In connection with the proposed acquisition and required stockholder
   approval, Sourcefire will file with the Securities and Exchange
   Commission a preliminary proxy statement and a definitive proxy
   statement. The proxy statement will be mailed to the stockholders of
   Sourcefire. Sourcefire's stockholders are urged to read the proxy
   statement (including all amendments and supplements) and other relevant
   materials when they become available because they will contain
   important information. Investors may obtain free copies of these
   documents (when they are available) and other documents filed with the
   SEC at its web site at [28]http://www.sec.gov. In addition, investors
   may obtain free copies of the documents filed with the SEC by
   Sourcefire by going to Sourcefire's Investor Relations page on its
   corporate website at [29]http://investor.sourcefire.com/ or by
   directing a request to Sourcefire at: Sourcefire, 9770 Patuxent Woods
   Drive, Columbia, MD 21046.

   Sourcefire and its officers and directors and other members of
   management and employees may be deemed to be participants in the
   solicitation of proxies from Sourcefire's stockholders with respect to
   the acquisition. Information about Sourcefire's executive officers and
   directors is set forth in the proxy statement for the Sourcefire 2013
   Annual Meeting of Stockholders, which was filed with the SEC on April
   24, 2013. Investors may obtain more detailed information regarding the
   direct and indirect interests of Sourcefire and its respective
   executive officers and directors in the acquisition by reading the
   preliminary and definitive proxy statements regarding the transaction,
   which will be filed with the SEC.

   In addition, Cisco and its officers and directors may be deemed to have
   participated in the solicitation of proxies from Sourcefire's
   stockholders in favor of the approval of the transaction. Information
   concerning Cisco's directors and executive officers is set forth in
   Cisco's proxy statement for its 2012 Annual Meeting of Shareholders,
   which was filed with the SEC on September 26, 2012, annual report on
   Form 10-K filed with the SEC on September 12, 2012, Form 8-K filed with
   the SEC on February 1, 2013, and Form 8-K filed with the SEC on October
   4, 2012. These documents are available free of charge at the SEC's
   website at [30]www.sec.gov or by going to Cisco's Investor Relations
   website at [31]http://www.cisco.com/go/investors.

   RSS Feed for Cisco: [32]http://newsroom.cisco.com/rss-feeds

   IFRAME: [33]//www.bankrate.com/widgets/yho/rate-table-story.aspx

   (BUTTON)
   Reblog
   (BUTTON)
   Share
   (BUTTON)
   Tweet
   (BUTTON)
   Share

   ____________________

   (BUTTON)
   [34]Recently Viewed
   Your list is empty.

What to Read Next

     *

[35]Take a breath: Stocks slow down after a record-setting run
       Associated Press
     *

[36]Cisco profit beats on strong demand for security products
       Reuters
     *

[37]U.S. Equities Advance for Seventh Day as Bank Stocks Rally
       Bloomberg
     *

[38]Cisco shares gain in choppy trade after earnings beat
       CNBC.com
     *

[39]Cisco earnings: Will big bets on software pay off?
       MarketWatch
     *

[40]'Morning Joe' host Mika Brzezinski: This is a 'fake presidency'
       Business Insider
     *

[41]A Trump order led the IRS to make a small change on Obamacare that could
have a big effect on its future
       Business Insider
     *

[42]Today's chart: UBS says now is the time to 'sell' Tesla
       Yahoo Finance
     *

[43]More retirees are choosing Medicare Advantage. Here's why
       CNBC.com
     *

[44]Fed's Lockhart Says Yellen Kept Options Open on Rates
       Bloomberg Video
     *

[45]Investors buzz over Snap's value and Puzder's flame out
       Yahoo Finance
     *

[46]Trump now owns Obamacare
       Yahoo Finance
     *

[47]Warren Buffett just dropped Walmart and signaled the death of retail as
we know it
       Business Insider
     *

[48]Charlie Munger: Here's the real mistake Wells Fargo made
       Yahoo Finance
     *

[49]Venezuela pulls Spanish-language CNN from air for 'distorting truth'
       Reuters
     *

[50]Why previously underwater homeowners can finally breathe a sigh of relief
       Yahoo Finance Video

   [51][spaceball.gif]

   EPA staff told to prepare for Trump executive orders: sources

     * [spaceball.gif]
     * [spaceball.gif]
     * [spaceball.gif]

   [52]

   AndrewG: I'm sorry, but I like having clean water to drink and clean
   air to breathe, as opposed to being tainted with toxins and
   carcinogens.
   [53]Join the Conversation
   (BUTTON) 1 / 5 (BUTTON)

   1k
     *

[54]Claims and starts — What you need to know in markets on Thursday
       Yahoo Finance
     *

[55]CHARLIE MUNGER: I've mellowed on Trump and he's 'not wrong on everything'
       Yahoo Finance
     *

[56]A 7-year-old girl asked Google for a job and got a personal response from
CEO Sundar Pichai
       Business Insider

     *

[57]Stock pickers beware: Berkshire Hathaway's Charlie Munger thinks you're
in big trouble
       CNBC
     *

[58]Workers at Boeing's South Carolina plant reject union
       Reuters
     *

[59]Trump: Never been a presidency that's done so much in sho...
       CNBC Videos
     *

[60]Retirement can be a drag. Here's how to fix that
       Associated Press
     *

[61]BUFFETT: What I tell people who are anti-immigration
       Yahoo Finance
     *

[62]4 tax breaks every parent should know about
       Yahoo Finance
     *

[63]Oil down 1 percent despite news OPEC could extend output cut
       Reuters
     *

[64]Why Trump's immigration policy could backfire
       Yahoo Finance Video
     *

[65]Trump suggests the stock market surge is just getting started
       Yahoo Finance
     *

[66]Warren Buffett: Your business will succeed if you execute this 3-word
mission
       Yahoo Finance
     *

[67]Dell XPS 13 2-in-1 review: The best laptop around learns a new trick
       Yahoo Finance
     *

[68]Mortgage Interest Tax Deductions May Get Extra Scrutiny This Year
       Kiplinger.com
     *

[69]Trump: Jobs would have left if I didn't get elected
       CNBC Videos

     * [70]Data Disclaimer
     * [71]Help
     * [72]Suggestions

References

   Visible links
   1. https://mail.yahoo.com/?.intl=us&.lang=en-US
   2. https://www.flickr.com/
   3. https://www.tumblr.com/
   4. https://www.yahoo.com/news/
   5. http://sports.yahoo.com/
   6. http://finance.yahoo.com/
   7. https://www.yahoo.com/celebrity/
   8. https://answers.yahoo.com/
   9. https://groups.yahoo.com/
  10. https://mobile.yahoo.com/
  11. http://everything.yahoo.com/
  12. https://www.mozilla.org/firefox/new/?utm_source=yahoo&utm_medium=referral&utm_campaign=y-uh&utm_content=y-finance-try
  13. https://finance.yahoo.com/
  14. https://login.yahoo.com/config/login?.intl=us&.lang=en-US&.src=finance&.done=http://finance.yahoo.com/news/cisco-announces-agreement-acquire-sourcefire-120000871.html
  15. https://mail.yahoo.com/?.intl=us&.lang=en-US&.partner=none&.src=finance
  16. https://finance.yahoo.com/
  17. https://finance.yahoo.com/personal-finance
  18. https://www.yahoo.com/tech
  19. https://finance.yahoo.com/portfolios?bypass=true
  20. https://finance.yahoo.com/quote/^GSPC?p=^GSPC
  21. https://finance.yahoo.com/quote/^DJI?p=^DJI
  22. http://www.marketwired.com/
  23. http://www.marketwired.com/
  24. http://ctt.marketwire.com/?release=1036368&id=3238291&type=1&url=http://investor.cisco.com/
  25. http://ctt.marketwire.com/?release=1036368&id=3238294&type=1&url=http://thenetwork.cisco.com/
  26. http://ctt.marketwire.com/?release=1036368&id=3238297&type=1&url=http://www.sourcefire.com/
  27. http://ctt.marketwire.com/?release=1036368&id=3238300&type=1&url=http://www.cisco.com/go/trademarks
  28. http://ctt.marketwire.com/?release=1036368&id=3238303&type=1&url=http://www.sec.gov/
  29. http://ctt.marketwire.com/?release=1036368&id=3238306&type=1&url=http://investor.sourcefire.com/
  30. http://ctt.marketwire.com/?release=1036368&id=3238309&type=1&url=http://www.sec.gov/
  31. http://ctt.marketwire.com/?release=1036368&id=3238312&type=1&url=http://www.cisco.com/go/investors
  32. http://ctt.marketwire.com/?release=1036368&id=3238315&type=1&url=http://newsroom.cisco.com/rss-feeds
  33. file://www.bankrate.com/widgets/yho/rate-table-story.aspx
  34. file:///recent-quotes
  35. file:///news/breath-stocks-slow-down-record-152707829.html
  36. file:///news/cisco-revenue-slips-fifth-straight-quarter-211501018--finance.html
  37. file:///m/1a007dda-cfb9-3cca-addf-eaa311c0a7f0/u.s.-equities-advance-for.html
  38. file:///m/80e0ef3e-73b2-3241-91b4-3d8553950451/cisco-shares-gain-in-choppy.html
  39. file:///m/4fccdc4e-71f5-3cad-9865-8f3015c43d6f/cisco-earnings:-will-big-bets.html
  40. file:///news/morning-joe-host-fake-presidency-172555218.html
  41. file:///news/trump-order-led-irs-small-205739364.html
  42. file:///news/todays-chart-ubs-says-now-is-the-time-to-sell-tesla-175840429.html
  43. file:///m/8f100a64-c2b6-3008-8fb3-704735b5dd70/more-retirees-are-choosing.html
  44. file:///video/feds-lockhart-says-yellen-kept-182223585.html
  45. file:///news/investors-loving-the-broken-record-of-record-breaking-as-they-buzz-over-snaps-value-and-puzders-flameout-132423152.html
  46. file:///news/trump-now-owns-obamacare-181736930.html
  47. file:///news/warren-buffett-just-dropped-walmart-225521054.html
  48. file:///news/charlie-munger-heres-the-real-mistake-wells-fargo-made-153842430.html
  49. file:///news/venezuela-pulls-spanish-language-cnn-air-distorting-truth-004218701--finance.html
  50. file:///video/why-previously-underwater-homeowners-finally-182259483.html
  51. file:///news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
  52. file:///news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
  53. file:///news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
  54. file:///news/claims-and-starts-what-you-need-to-know-in-markets-on-thursday-025535082.html
  55. file:///news/charlie-munger-ive-mellowed-on-trump-and-hes-not-wrong-on-everything-132536555.html
  56. file:///news/7-old-girl-asked-google-190303812.html
  57. file:///news/stock-pickers-beware-berkshire-hathaways-204942226.html
  58. file:///news/boeing-wins-union-vote-south-carolina-plant-013406053--finance.html
  59. file:///video/trump-never-presidency-thats-done-181800176.html
  60. file:///news/retirement-drag-heres-fix-150635513.html
  61. file:///news/buffett-what-i-tell-people-who-are-anti-immigration-224409573.html
  62. file:///news/4-basic-tax-breaks-every-parent-should-know-about-150940602.html
  63. file:///news/oil-prices-steady-opec-cuts-031304367.html
  64. file:///video/why-trumps-immigration-policy-could-181759397.html
  65. file:///news/trump-suggests-the-stock-market-surge-is-just-getting-started-155544205.html
  66. file:///news/warren-buffett-best-advice-for-small-business-owners-203913790.html
  67. file:///news/dell-xps-13-2-in-1-review-182128506.html
  68. file:///m/74e92543-9559-30dd-9f83-d4be0756ecdb/mortgage-interest-tax.html
  69. file:///video/trump-jobs-left-didnt-elected-181600152.html
  70. https://help.yahoo.com/kb/finance/SLN2310.html?impressions=true
  71. http://help.yahoo.com/l/us/yahoo/finance/
  72. http://yahoo.uservoice.com/forums/207809

   Hidden links:
  74. https://www.yahoo.com/
  75. https://finance.yahoo.com/screener
  76. https://finance.yahoo.com/chart/^GSPC
  77. https://finance.yahoo.com/chart/^DJI
  78. file://localhost/news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
  79. file://localhost/news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
  80. file://localhost/news/epa-staff-told-prepare-trump-executive-orders-sources-011248526.html?.tsrc=jtc_news_article
